### PR TITLE
API juices are flowing!

### PR DESCRIPTION
**Pull request by seyah**
Commits are self explanatory. Very near, if not already, good for a release. Got a mini API started with some custom events to go alongside it. I believe all static references are gone now in true OOP style. I also think I've found a good packaging order to suit the introduction of the NMS packages and the API to the point "it makes sense where bits would be". Got an ENUM DragonType - used mainly in the functions and API, less so in the RyeDragon. Made it 1.7 compliant too. And it compiles!

### CODE REVIEW

**Comment by Phiwa** [comment]
Good job mate! :+1:

**Comment by seyah** [comment]
Not so fast! Check the plugin.yml mine was a bit odd!

**Comment by Phiwa** [comment]
I trusted you...and you failed me. :(

**Comment by seyah** [comment]
I blame IntelliJ entirely :P

**Pull request merged**
