### PR TITLE
Initial Commit of Towny Town Spawn Support

### PR DESCRIPTION
**Pull request by DrkMatr1984**
Everything works, might need some official phiwa touchup ;) Only thing is if you have Towny set to remove EnderDragons in the Towny config, it will remove DragonTravel dragons regardless of the various measures I tried to stop it from doing so. The default Towny config doesn't remove EnderDragons, so most users won't notice an issue, but my server has Enderdragons in the overworld and the removal of them when attacking towns is sometimes necessary. See if you can get it to allow EnderDragons to spawn despite the settings? Check out TownyListener.java

### CODE REVIEW

**Comment by Phiwa** [comment]
Looks great, thanks! :)
As soon as I find some spare time, I'll pull it, test it and probably merge it. :+1:

**Comment by Phiwa** [comment]
Hey mate, I just manually merged your PR. Thank you for your work, we now have support for Towny which will be included in the next release! :) :+1:

**Comment by DrkMatr1984** [comment]
:) Nice, Thanks for taking the time to review the changes :)

**Comment by DrkMatr1984** [comment]
I was gonna merge the changes into my branch but I just decided to delete my fork and refork your master branch. If I get time soon I may add a method into the towny support for doing "/dt tspawn <TownName>" so towny users may use DragonTravel to travel between towns that are not their own.

**Pull request closed without merging**
